
package mw.pathclient;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "MWNoSuchKeyException", targetNamespace = "http://path.mw/")
public class MWNoSuchKeyException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private MWNoSuchKeyException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public MWNoSuchKeyException_Exception(String message, MWNoSuchKeyException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public MWNoSuchKeyException_Exception(String message, MWNoSuchKeyException faultInfo, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: mw.pathclient.MWNoSuchKeyException
     */
    public MWNoSuchKeyException getFaultInfo() {
        return faultInfo;
    }

}
